version: '3'
services:
     web:
        image: nginx:latest
        ports:
           - "86:80"
        volumes:
           - ./code:/code
           - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
        links:
           - php
     php:
        build: . 
        ports:
        - 9000:9000
        volumes:
           - ./code:/code
           - /home/tamil/new-compose/php/fpm:/etc/php/7.2/fpm
        links:
           - mysql
        
     mysql:
        build: ./my/.
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: newsportal
          
        volumes:
           - ./newsportal.sql:/docker-entrypoint-initdb.d/newsportal.sql
           - mysql1:/var/lib/mysql
            
        ports:
          -  "3308:3306"

volumes:
 mysql1:

