kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;
        
        # Set nginx to serve files from the shared volume!
        root /var/www/html;
        index index.php index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
          try_files $uri $uri/ =404;
          
          
        }
        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ec2-user"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: mc3
  labels:
    app: mc3
spec:
  volumes:    
    - name: nginx-config-volume
      configMap:
        name: nginx-config
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  
  containers:
     
      
    - image: nginx
      name: nginx
      ports:
      - containerPort: 80
      volumeMounts:
        - name: task-pv-storage
          mountPath: /var/www/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        
    - image: talsan/my-php:tagVersion 
      imagePullPolicy: IfNotPresent      
      name: app
      volumeMounts:
        - name: task-pv-storage
          mountPath: /var/www/html 
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: mc3
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
